name: ci

on:
  - push
  - workflow_dispatch

env:
  MAVEN_FLAGS: "-B --no-transfer-progress"
  MAVEN_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000 -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3"

jobs:
  ci:
    uses: killbill/gh-actions-shared/.github/workflows/ci.yml@main
    with:
      test-profile-matrix: '[ "travis" ]'
      jdk-matrix: '[ "8", "11" ]'
