name: ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    uses: killbill/gh-actions-shared/.github/workflows/ci.yml@main
    
integration_test:
    uses: killbill/gh-actions-shared/.github/workflows/integration_test.yml@main
    with:
      plugin_name: 'catalog-plugin-test'
      integration_tests_goal: 'test:plugins:catalog-plugin-test'
      integration_tests_ref: 'refs/heads/work-for-release-0.23.x'    

