name: ci

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    uses: killbill/gh-actions-shared/.github/workflows/ci.yml@main  

  integration_test:
    uses: killbill/gh-actions-shared/.github/workflows/integration_test.yml@main
    with:
      plugin_name: 'catalog-test'
      integration_tests_goal: 'test:plugins:catalog-test'
      integration_tests_ref: 'refs/heads/master'    